import { displayDate } from "../format";
import { guidanceContext, withoutGoalPrefix } from "../hale-guidance";
import type { Guidance, RecommendationItem } from "../types";

interface HaleBriefingProps {
  guidance: Guidance;
  onOpen: () => void;
}

export function HaleBriefing({ guidance, onOpen }: HaleBriefingProps) {
  const primaryItem = guidance.items[0];
  const remainingCount = Math.max(0, guidance.items.length - 1);

  return (
    <section className="hale-briefing" aria-labelledby="hale-briefing-title">
      <header className="hale-briefing-header">
        <div>
          <h3 id="hale-briefing-title">Hale</h3>
          <GuidanceMeta guidance={guidance} />
        </div>
      </header>

      <p className="hale-briefing-context">{guidanceContext(guidance)}</p>

      <div className="hale-briefing-summary">
        <span className="metric-label">This week</span>
        <p>{withoutGoalPrefix(guidance.summaries.weekly)}</p>
      </div>

      {primaryItem ? (
        <PrimaryGuidance item={primaryItem} />
      ) : (
        <p className="muted-text">No guidance is available yet.</p>
      )}

      <footer className="hale-briefing-footer">
        <button className="text-button" type="button" onClick={onOpen}>Open Hale</button>
        {remainingCount > 0 && (
          <span>{remainingCount} more {remainingCount === 1 ? "recommendation" : "recommendations"}</span>
        )}
      </footer>
    </section>
  );
}

export function GuidanceMeta({ guidance }: { guidance: Guidance }) {
  return (
    <div className="hale-guidance-meta">
      <GuidanceSource guidance={guidance} />
      <span>Updated {displayDate(guidance.generatedAt)}</span>
    </div>
  );
}

export function GuidanceSource({ guidance }: { guidance: Guidance }) {
  return (
    <span className={`source-label ${guidance.source === "deepseek" ? "ai-source" : "local-source"}`}>
      {guidance.source === "deepseek" ? "AI generated by DeepSeek" : "Local guidance"}
    </span>
  );
}

export function PrimaryGuidance({ item }: { item: RecommendationItem }) {
  return (
    <article className="hale-primary-guidance">
      <span className={`priority priority-${item.priority}`}>{item.priority}</span>
      <div>
        <strong>{item.title}</strong>
        <p>{withoutGoalPrefix(item.text)}</p>
      </div>
    </article>
  );
}
